coffee_detect:
  ros__parameters:
    sam_checkpoint: "/home/wzb/ros2ws/coffee_ws/src/coffee_detect/sam/sam_vit_h_4b8939.pth"
    device: "cuda"
    camera_fx: 490.2380676269531
    camera_fy: 490.2380676269531
    camera_cx: 316.89483642578125
    camera_cy: 209.28350830078125
    min_area: 1000
    handeye_pos: [-0.07482322180223497, 0.00623968754635619, 0.050192986145776636]
    handeye_quat: [-0.1197419547833481, 0.12550407599676805, -0.7127657428175671, 0.6796142928445386]