arm:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_timeout: 0.05
  solve_type: Distance  # 关键！当无法精确满足时，返回最近解
gripper:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_timeout: 0.05
  solve_type: Distance  # 关键！当无法精确满足时，返回最近解
# arm:
#   kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#   kinematics_solver_search_resolution: 0.0050000000000000001
#   kinematics_solver_timeout: 0.0050000000000000001
# gripper:
#   kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#   kinematics_solver_search_resolution: 0.0050000000000000001
#   kinematics_solver_timeout: 0.0050000000000000001